{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pebbles
  version: {{ GIT_DESCRIBE_TAG }}

source:

  git_url: https://github.com/pdiakumis/pebbles
  git_tag: master

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pebbles')"           # [not win]
    - "\"%R%\" -e \"library('pebbles')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/pdiakumis/pebbles
  license: MIT + file LICENSE
  summary: Contains cancer genomics datasets for running tests and examples in the rock R package
    (https://github.com/umccr/rock).
  license_family: MIT
